{% raw %}

name: Release and deploy

on:
  create:
    tags:
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install pipenv tox

      - name: Run tests
        run: tox

  publish:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
{% endraw %}
          name: {{ cookiecutter.docker_image_name }}
{% raw %}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true

  deploy:
    needs: [publish_image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Prepare ansible config secrets
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir .ssh
          echo "$SSH_KEY" > .ssh/id_rsa
          chmod 600 .ssh/id_rsa

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Deploy new version
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          SHORTNER_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          ansible-playbook -i ansible/inventory ansible/deploy.yml

      - name: Send notification to Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ github.repository }} deploy version `${{ steps.vars.outputs.tag }}` - ${{ job.status }}


{% endraw %}
