---
language: python
python:
  - "3.6"

branches:
  only:
  - master

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install tox

script:
  - tox

after_success:
  # Build image and publish image
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    make build-image;
    make publish-image;
    fi
